import type { ViralStudioEditorProps } from "./EditableViralVideo";

export type ViralEditorPresetId =
  | "ガチで脱いだ女性芸能人3選-20260313"
  | "事務所に売られた芸能人3選-20260316";

export type ViralEditorPreset = {
  id: ViralEditorPresetId;
  label: string;
  storageKey: string;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
  props: ViralStudioEditorProps;
};

const sharedStyle: ViralStudioEditorProps["style"] = {
  textColor: "#ffffff",
  strokeColor: "#000000",
  outerStrokeColor: "#ffffff",
  dropShadow: "0 4px 0 rgba(0,0,0,0.85), 0 8px 20px rgba(0,0,0,0.65)",
  subtitleFontSize: 140,
  nameCardFontSize: 170,
  subtitleXPercent: 50,
  subtitleYPercent: 55,
  subtitleMaxWidthPercent: 100,
  subtitleLineGap: 12,
  subtitleLineHeight: 1.1,
  subtitleEnterScaleFrom: 0.88,
  subtitleFadeInFrames: 6,
  strokeWidthPx: 1.5,
  outerStrokeWidthPx: 20,
  nameCardOuterStrokeWidthPx: 22,
  hookFontSize: 160,
  hookPaddingTopPercent: 65,
  hookLineColors: ["#f4d56f", "#f4a898", "#f0c8d8", "#ffffff"],
  nameLineColors: ["#FFE400", "#FFE400"],
  flashOpacity: 0.3,
};

export const viralEditorPresets: ViralEditorPreset[] = [
  {
    id: "ガチで脱いだ女性芸能人3選-20260313",
    label: "ガチで脱いだ女性芸能人3選",
    storageKey: "viral-editor-gachi-20260313",
    durationInFrames: 1887,
    fps: 30,
    width: 1080,
    height: 1920,
    props: {
      audioSrc: "viral/ガチで脱いだ女性芸能人3選_20260313/audio/narration.wav",
      hookDurationFrames: 90,
      fadeFrames: 12,
      flashDurationFrames: 6,
      scenes: [
        {
          from: 0,
          to: 90,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/00_hook.png",
          motionType: "zoom_in",
          motionProfile: "gentle",
          motionIntensity: 0.5,
          originX: 0.5,
          originY: 0.4,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 90,
          to: 258,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/02_s1_1.png",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
          flashOnEnter: true,
        },
        {
          from: 258,
          to: 462,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/02_s1_2.png",
          motionType: "pan_right",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.4,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 462,
          to: 586,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/02_s1_3.png",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 586,
          to: 733,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/03_s2_1.png",
          motionType: "zoom_in",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.5,
          originY: 0.4,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
          flashOnEnter: true,
        },
        {
          from: 733,
          to: 1036,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/03_s2_2.png",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 1036,
          to: 1153,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/03_s2_3.png",
          motionType: "pan_left",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.6,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 1153,
          to: 1333,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/04_s3_1.png",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
          flashOnEnter: true,
        },
        {
          from: 1333,
          to: 1481,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/04_s3_2.png",
          motionType: "zoom_out",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.5,
          originY: 0.4,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 1481,
          to: 1617,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/04_s3_3.png",
          motionType: "pan_right",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.4,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 1617,
          to: 1887,
          src: "viral/ガチで脱いだ女性芸能人3選_20260313/materials/99_cta.png",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
      ],
      subtitles: [
        { from: 0, to: 82, text: "ガチで\n脱いだ\n女性芸能人\n3選" },
        { from: 90, to: 138, text: "1.釈由美子" },
        { from: 138, to: 186, text: "デビュー\n直後から" },
        { from: 186, to: 222, text: "過激な\nグラビアを" },
        { from: 222, to: 258, text: "連発し、" },
        { from: 258, to: 303, text: "写真集の\n売上は" },
        { from: 303, to: 348, text: "100万部\nを突破。" },
        { from: 348, to: 405, text: "あの清純\nそうな顔で" },
        { from: 405, to: 462, text: "何をやって\nいたのか。" },
        { from: 462, to: 503, text: "当時の\n写真集は" },
        { from: 503, to: 545, text: "今でも\n高値で" },
        { from: 545, to: 586, text: "取引されて\nいる。" },
        { from: 586, to: 642, text: "2.杉本彩" },
        { from: 642, to: 710, text: "映画\n愛の流刑地" },
        { from: 710, to: 733, text: "で見せた" },
        { from: 733, to: 790, text: "全力の\n脱ぎっぷり" },
        { from: 790, to: 860, text: "は業界を\n震撼させた。" },
        { from: 860, to: 908, text: "美しすぎる\n40代の" },
        { from: 908, to: 958, text: "裸体が\n話題となり" },
        { from: 958, to: 1036, text: "作品は\n大ヒット。" },
        { from: 1036, to: 1078, text: "今でも\nその潔さを" },
        { from: 1078, to: 1117, text: "称える声が\n後を絶た" },
        { from: 1117, to: 1153, text: "ない。" },
        { from: 1153, to: 1209, text: "3.安達祐実" },
        { from: 1209, to: 1250, text: "子役出身の\n清純派と" },
        { from: 1250, to: 1292, text: "いう\nイメージが" },
        { from: 1292, to: 1333, text: "強いが、" },
        { from: 1333, to: 1385, text: "20代で\n発売した" },
        { from: 1385, to: 1432, text: "写真集は\nグラビア界" },
        { from: 1432, to: 1481, text: "に衝撃を\n与えた。" },
        { from: 1481, to: 1530, text: "ギャップの\n大きさが" },
        { from: 1530, to: 1565, text: "話題を\n呼び、" },
        { from: 1565, to: 1617, text: "完売が\n相次いだ。" },
        { from: 1617, to: 1651, text: "以上、\nガチで" },
        { from: 1651, to: 1686, text: "脱いだ\n女性芸能人" },
        { from: 1686, to: 1720, text: "3選でした。" },
        { from: 1720, to: 1762, text: "他にも\n気になる" },
        { from: 1762, to: 1804, text: "芸能人が\nいたら" },
        { from: 1804, to: 1845, text: "フォロー\nして" },
        { from: 1845, to: 1887, text: "確認してみて\nください。" },
      ],
      style: sharedStyle,
    },
  },
  {
    id: "事務所に売られた芸能人3選-20260316",
    label: "事務所に売られた芸能人3選",
    storageKey: "viral-editor-jimusho-20260316",
    durationInFrames: 1550,
    fps: 30,
    width: 1080,
    height: 1920,
    props: {
      audioSrc: "viral/事務所に売られた芸能人3選/audio/narration.wav",
      hookDurationFrames: 50,
      fadeFrames: 12,
      flashDurationFrames: 6,
      scenes: [
        {
          from: 0,
          to: 62,
          src: "viral/事務所に売られた芸能人3選/materials/00_hook.jpg",
          motionType: "zoom_in",
          motionProfile: "gentle",
          motionIntensity: 0.5,
          originX: 0.5,
          originY: 0.4,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 62,
          to: 206,
          src: "viral/事務所に売られた芸能人3選/materials/01_s1_1.jpg",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
          flashOnEnter: true,
        },
        {
          from: 206,
          to: 350,
          src: "viral/事務所に売られた芸能人3選/materials/01_s1_2.jpg",
          motionType: "pan_right",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.4,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 350,
          to: 494,
          src: "viral/事務所に売られた芸能人3選/materials/01_s1_3.jpg",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 494,
          to: 652,
          src: "viral/事務所に売られた芸能人3選/materials/02_s2_1.jpg",
          motionType: "zoom_in",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.5,
          originY: 0.4,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
          flashOnEnter: true,
        },
        {
          from: 652,
          to: 810,
          src: "viral/事務所に売られた芸能人3選/materials/02_s2_2.jpg",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 810,
          to: 969,
          src: "viral/事務所に売られた芸能人3選/materials/02_s2_3.jpg",
          motionType: "pan_left",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.6,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 969,
          to: 1106,
          src: "viral/事務所に売られた芸能人3選/materials/03_s3_1.jpg",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
          flashOnEnter: true,
        },
        {
          from: 1106,
          to: 1243,
          src: "viral/事務所に売られた芸能人3選/materials/03_s3_2.jpg",
          motionType: "zoom_out",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.5,
          originY: 0.4,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 1243,
          to: 1379,
          src: "viral/事務所に売られた芸能人3選/materials/03_s3_3.jpg",
          motionType: "pan_right",
          motionProfile: "gentle",
          motionIntensity: 0.4,
          originX: 0.4,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
        {
          from: 1379,
          to: 1550,
          src: "viral/事務所に売られた芸能人3選/materials/99_cta.jpg",
          motionType: "static",
          motionProfile: "still",
          motionIntensity: 0,
          originX: 0.5,
          originY: 0.5,
          baseScale: 1,
          cropXPercent: 0,
          cropYPercent: 0,
        },
      ],
      subtitles: [
        { from: 0, to: 50, text: "事務所に\n売られた\n芸能人\n3選" },
        { from: 62, to: 94, text: "1.清水富美加" },
        { from: 94, to: 124, text: "所属事務所から\n過密" },
        { from: 156, to: 199, text: "スケジュールを\n強いられ続け" },
        { from: 199, to: 236, text: "年間100本\n超えの仕事を" },
        { from: 236, to: 269, text: "本人の意志とは\n無関係に" },
        { from: 272, to: 311, text: "限界を超えた\n彼女は突如" },
        { from: 311, to: 341, text: "引退を宣言" },
        { from: 341, to: 442, text: "事務所との\n確執が世間を" },
        { from: 442, to: 487, text: "震撼させた" },
        { from: 494, to: 526, text: "2.能年玲奈" },
        { from: 526, to: 577, text: "NHK朝ドラで\n国民的人気を" },
        { from: 598, to: 623, text: "得た直後" },
        { from: 623, to: 669, text: "事務所の意向で\n活動を徹底的に" },
        { from: 677, to: 695, text: "制限された" },
        { from: 695, to: 732, text: "本名すら\n使えなくなり" },
        { from: 758, to: 794, text: "「のん」として\n再出発" },
        { from: 794, to: 842, text: "業界の闇を\n全国に" },
        { from: 842, to: 913, text: "知らしめた\n一件として今も" },
        { from: 937, to: 969, text: "語り継がれて\nいる" },
        { from: 969, to: 1009, text: "3.飯島直子" },
        { from: 1009, to: 1039, text: "デビュー当初\nから過激な" },
        { from: 1051, to: 1082, text: "グラビアを\n量産させられた" },
        { from: 1091, to: 1125, text: "「やりたく\nなかった」と" },
        { from: 1125, to: 1155, text: "後年告白" },
        { from: 1155, to: 1209, text: "それでも\n生き残るために" },
        { from: 1209, to: 1259, text: "従うしか\nなかった" },
        { from: 1259, to: 1373, text: "芸能界の現実が\nそこにあった" },
        { from: 1376, to: 1413, text: "以上、\n事務所に" },
        { from: 1413, to: 1443, text: "売られた\n芸能人3選" },
        { from: 1506, to: 1532, text: "フォローして\nチェックして" },
        { from: 1532, to: 1550, text: "みてください" },
      ],
      style: sharedStyle,
    },
  },
];

export const getViralEditorPresetById = (presetId: string): ViralEditorPreset => {
  return viralEditorPresets.find((preset) => preset.id === presetId) ?? viralEditorPresets[0];
};
